export const data = {
    img: {
        coatPoland: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Herb_Polski.svg/764px-Herb_Polski.svg.png",
        coatLowerSilesian: "https://upload.wikimedia.org/wikipedia/commons/7/7a/POL_wojew%C3%B3dztwo_dolno%C5%9Bl%C4%85skie_COA.svg",
        coatKuyavianPomeranian: "https://upload.wikimedia.org/wikipedia/commons/7/79/POL_wojew%C3%B3dztwo_kujawsko-pomorskie_COA.svg",
        coatLublin: "https://upload.wikimedia.org/wikipedia/commons/4/4d/POL_wojew%C3%B3dztwo_lubelskie_COA.svg",
        coatLubusz: "https://upload.wikimedia.org/wikipedia/commons/c/c6/POL_wojew%C3%B3dztwo_lubuskie_COA.svg",
        coatLodz: "https://upload.wikimedia.org/wikipedia/commons/a/af/POL_wojew%C3%B3dztwo_%C5%82%C3%B3dzkie_COA.svg",
        coatLesserPoland: "https://upload.wikimedia.org/wikipedia/commons/d/d2/POL_wojew%C3%B3dztwo_ma%C5%82opolskie_COA.svg",
        coatMasovian: "https://upload.wikimedia.org/wikipedia/commons/6/69/POL_wojew%C3%B3dztwo_mazowieckie_COA.svg",
        coatOpole: "https://upload.wikimedia.org/wikipedia/commons/5/57/POL_wojew%C3%B3dztwo_opolskie_COA.svg",
        coatSubcarpathian: "https://upload.wikimedia.org/wikipedia/commons/6/61/POL_wojew%C3%B3dztwo_podkarpackie_COA.svg",
        coatPodlaskie: "https://upload.wikimedia.org/wikipedia/commons/e/e4/POL_województwo_podlaskie_COA.svg",
        coatPomeranian: "https://upload.wikimedia.org/wikipedia/commons/3/3b/POL_wojew%C3%B3dztwo_pomorskie_COA.svg",
        coatSilesian: "https://upload.wikimedia.org/wikipedia/commons/c/c9/POL_wojew%C3%B3dztwo_%C5%9Bl%C4%85skie_COA.svg",
        coatHolyCross: "https://upload.wikimedia.org/wikipedia/commons/3/36/POL_wojew%C3%B3dztwo_%C5%9Bwi%C4%99tokrzyskie_COA.svg",
        coatWarmianMasurian: "https://upload.wikimedia.org/wikipedia/commons/e/eb/Warminsko-mazurskie_herb.svg",
        coatGreaterPoland: "https://upload.wikimedia.org/wikipedia/commons/7/7b/POL_wojew%C3%B3dztwo_wielkopolskie_COA.svg",
        coatWestPomeranian: "https://upload.wikimedia.org/wikipedia/commons/4/47/POL_wojew%C3%B3dztwo_zachodniopomorskie_COA.svg",
    },
    welcome: {
        title: "Palatinus",
        left: {
            line0: "Welcome to Palatinus!",
            line1: "Palatinus is a visual portal about Polish voivodeships.",
            line2: "Here you can find interesting information about various regions of the Republic and learn some historical facts.",
            line3: "If you'd like to visit my other project about the Opole Voivodeship, please click the link below.",
            button: "Learn about Opole",
        },
        right: {
            line0: "Information Feed",
            line1: "Requested information will be displayed here. You can request for information by clicking on the desired voivodeship."
        },
    },
    voivodeships: {
        names: {
            LowerSilesian: "Lower Silesian",
            KuyavianPomeranian: "Kuyavian-Pomeranian",
            Lublin: "Lublin",
            Lubusz: "Lubusz",
            Lodz: "Łódź",
            LesserPoland: "Lesser Poland",
            Masovian: "Masovian",
            Opole: "Opole",
            Subcarpathian: "Subcarpathian",
            Podlaskie: "Podlaskie",
            Pomeranian: "Pomeranian",
            Silesian: "Silesian",
            HolyCross: "Holy Cross",
            WarmianMasurian: "Warmian-Masurian",
            GreaterPoland: "Greater Poland",
            WestPomeranian: "West Pomeranian",
        },
        info: {
            LowerSilesian: "Lower Silesian Voivodeship, or Lower Silesia Province (Polish: województwo dolnośląskie [vɔjɛˈvut͡stfɔ dɔlnɔˈɕlɔ̃skʲɛ]) in southwestern Poland, is one of the 16 voivodeships (provinces) into which Poland is divided.\nThe history of the region dates back over a thousand years and Lower Silesia was once part of Medieval Poland, Bohemia, Austria, Prussia, Germany and modern Poland after 1945.",
            KuyavianPomeranian: "Kuyavian-Pomeranian Voivodeship, also known as Cuiavian-Pomeranian Voivodeship or simply Kujawsko-Pomorskie, or Kujawy-Pomerania Province (Polish: województwo kujawsko-pomorskie [vɔjɛˈvut͡stfɔ kuˈjafskɔ pɔˈmɔrskʲɛ]; German: Woiwodschaft Kujawien-Pommern is one of the 16 voivodeships (provinces) into which Poland is divided. It was created on 1 January 1999 and is situated in mid-northern Poland.",
            Lublin: "Lublin Voivodeship, or Lublin Province (in Polish, województwo lubelskie [vɔjɛˈvut͡stfɔ luˈbɛlskʲɛ]), is a voivodeship, or region, located in southeastern Poland. It was created on January 1, 1999, out of the former Lublin, Chełm, Zamość, Biała Podlaska and (partially) Tarnobrzeg and Siedlce Voivodeships, pursuant to Polish local government reforms adopted in 1998.",
            Lubusz: "Lubusz Voivodeship, or Lubusz Province (Polish: województwo lubuskie [vɔjɛˈvut͡stfɔ luˈbuskʲɛ], German: Woiwodschaft Lebus), is a voivodeship (province) in western Poland.\nIt was created on January 1, 1999, out of the former Gorzów Wielkopolski and Zielona Góra Voivodeships, pursuant to the Polish local government reforms adopted in 1998. The province's name recalls the historic Lubusz Land (Lebus or Lubus).",
            Lodz: "Łódź Voivodeship (also known as Łódź Province, or by its Polish name, Województwo Łódzkie [vɔjɛˈvut͡stfɔ ˈwut͡skʲɛ]) or Ziemia Łódzka is a province (voivodeship) in central Poland. It was created on 1 January 1999 out of the former Łódź Voivodeship (1975–1999) and the Sieradz, Piotrków Trybunalski and Skierniewice Voivodeships and part of Płock Voivodeship, pursuant to the Polish local government reforms adopted in 1998.",
            LesserPoland: "Lesser Poland Voivodeship or Lesser Poland Province (in Polish: województwo małopolskie [vɔjɛˈvut͡stfɔ mawɔˈpɔlskʲɛ]), also known as Małopolska, is a voivodeship (province), in southern Poland. It has an area of 15,108 square kilometres (5,833 sq mi), and a population of 3,267,731 (2006).",
            Masovian: "Mazovian Voivodeship or Mazovia Province (Polish: województwo mazowieckie [vɔjɛˈvut͡stfɔ mazɔˈvʲɛtskʲɛ]) is the largest and most populous of the 16 Polish provinces, or voivodeships, created in 1999. It occupies 35,579 square kilometres (13,737 sq mi) of east-central Poland, and has 5,324,500 inhabitants.",
            Opole: "Opole Voivodeship, or Opole Province (Polish: województwo opolskie [vɔjɛˈvutstfɔ ɔˈpɔlskʲɛ], German: Woiwodschaft Oppeln, Czech: Opolské vojvodství), is the smallest and least populated voivodeship (province) of Poland. The province's name derives from that of the region's capital and largest city, Opole.",
            Subcarpathian: "Podkarpackie Voivodeship or Podkarpackie Province (in Polish: województwo podkarpackie [vɔjɛˈvut͡stfɔ pɔtkarˈpatskʲɛ], Slovak: Podkarpatské vojvodstvo, Ukrainian: Підкарпатське воєводство), also known as Subcarpathian Voivodeship or Subcarpathia Province, is a voivodeship, or province, in southeastern corner of Poland.",
            Podlaskie: "Podlaskie Voivodeship or Podlasie Province (Polish: Województwo podlaskie, [vɔjɛˈvut͡stfɔ pɔdˈlaskʲɛ]; Lithuanian: Palenkės vaivadija; Belarusian: Падляскае ваяводства) is a voivodeship (province) in northeastern Poland.",
            Pomeranian: "Pomeranian Voivodeship, Pomorskie Region, or Pomerania Province (Polish: województwo pomorskie [vɔjɛˈvut͡stfɔ pɔˈmɔrskʲɛ]; German: Woiwodschaft Pommern Kashubian Pòmòrsczé wòjewództwò), is a voivodeship, or province, in northwestern Poland. The provincial capital is Gdańsk.",
            Silesian: "Silesian Voivodeship, or Silesia Province (Polish: województwo śląskie [vɔjɛˈvut͡stfɔ ˈɕlɔ̃skʲɛ]; German: Woiwodschaft Schlesien; Czech: Slezské vojvodství) is a voivodeship, or province, in southern Poland, centered on the historic region known as Upper Silesia (Górny Śląsk), with Katowice serving as its capital.",
            HolyCross: "Świętokrzyskie Voivodeship, Świętokrzyskie Province, or Holy Cross Province (Polish: województwo świętokrzyskie [vɔjɛˈvut͡stfɔ ɕfʲɛntɔˈkʂɨskʲɛ]) is one of the 16 voivodeships (provinces) into which Poland is divided. It is situated in southeastern Poland, in the historical region of Lesser Poland, and takes its name from the Świętokrzyskie (Holy Cross) mountain range.",
            WarmianMasurian: "Warmian-Masurian Voivodeship or Warmia-Masuria Province or Warmia-Mazury Province (in Polish: Województwo warmińsko-mazurskie, [vɔjɛˈvut͡stfɔ varˈmiɲskɔ maˈzurskʲɛ] is a voivodeship (province) in northeastern Poland. Its capital and largest city is Olsztyn.",
            GreaterPoland: "Greater Poland Voivodeship (in Polish: Województwo Wielkopolskie [vɔjɛˈvut͡stfɔ vjɛlkɔˈpɔlskʲɛ]), also known as Wielkopolska Voivodeship, Wielkopolska Province, or Greater Poland Province, German: Woiwodschaft Großpolen is a voivodeship, or province, in west-central Poland.",
            WestPomeranian: "West Pomeranian Voivodeship or West Pomerania Province (in Polish, województwo zachodniopomorskie [vɔjɛˈvut͡stfɔ zaˈxɔdɲɔ pɔˈmɔrskʲɛ]; is a voivodeship (province) in northwestern Poland. It borders on Pomeranian Voivodeship to the east, Greater Poland Voivodeship to the southeast, Lubusz Voivodeship to the south, the German federal-states of Mecklenburg-West Pomerania and Brandenburg to the west, and the Baltic Sea to the north.",
        },
        links: {
            LowerSilesian: "https://en.wikipedia.org/wiki/Lower_Silesian_Voivodeship",
            KuyavianPomeranian: "https://en.wikipedia.org/wiki/Kuyavian-Pomeranian_Voivodeship",
            Lublin: "https://en.wikipedia.org/wiki/Lublin_Voivodeship",
            Lubusz: "https://en.wikipedia.org/wiki/Lubusz_Voivodeship",
            Lodz: "https://en.wikipedia.org/wiki/%C5%81%C3%B3d%C5%BA_Voivodeship",
            LesserPoland: "https://en.wikipedia.org/wiki/Lesser_Poland_Voivodeship",
            Masovian: "https://en.wikipedia.org/wiki/Masovian_Voivodeship",
            Opole: "https://en.wikipedia.org/wiki/Opole_Voivodeship",
            Subcarpathian: "https://en.wikipedia.org/wiki/Podkarpackie_Voivodeship",
            Podlaskie: "https://en.wikipedia.org/wiki/Podlaskie_Voivodeship",
            Pomeranian: "https://en.wikipedia.org/wiki/Pomeranian_Voivodeship",
            Silesian: "https://en.wikipedia.org/wiki/Silesian_Voivodeship",
            HolyCross: "https://en.wikipedia.org/wiki/%C5%9Awi%C4%99tokrzyskie_Voivodeship",
            WarmianMasurian: "https://en.wikipedia.org/wiki/Warmian-Masurian_Voivodeship",
            GreaterPoland: "https://en.wikipedia.org/wiki/Warmian-Masurian_Voivodeship",
            WestPomeranian: "https://en.wikipedia.org/wiki/West_Pomeranian_Voivodeship",
        }
    },
}